{{- if .Values.openstack.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openstack-vm-recovery.secretName" . }}
  labels:
    {{- include "openstack-vm-recovery.labels" . | nindent 4 }}
type: Opaque
stringData:
  OS_AUTH_URL: {{ .Values.openstack.auth.OS_AUTH_URL | quote }}
  OS_USERNAME: {{ .Values.openstack.auth.OS_USERNAME | quote }}
  OS_PASSWORD: {{ .Values.openstack.auth.OS_PASSWORD | quote }}
  OS_PROJECT_NAME: {{ .Values.openstack.auth.OS_PROJECT_NAME | quote }}
  OS_USER_DOMAIN_NAME: {{ .Values.openstack.auth.OS_USER_DOMAIN_NAME | quote }}
  OS_PROJECT_DOMAIN_NAME: {{ .Values.openstack.auth.OS_PROJECT_DOMAIN_NAME | quote }}
  OS_IDENTITY_API_VERSION: {{ .Values.openstack.auth.OS_IDENTITY_API_VERSION | quote }}
  OS_AUTH_TYPE: {{ .Values.openstack.auth.OS_AUTH_TYPE | quote }}
{{- end }}
