{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ocp-k8s-diagnostic-mcp.serviceAccountName" . }}
  labels:
    {{- include "ocp-k8s-diagnostic-mcp.labels" . | nindent 4 }}
{{- end }}

