apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-ai-assistant.fullname" . }}-config
data:
  PROMETHEUS_URL: {{ .Values.config.PROMETHEUS_URL | quote }}
  AI_BACKEND_URL: {{ .Values.config.AI_BACKEND_URL | quote }}
  AI_MODEL_NAME: {{ .Values.config.AI_MODEL_NAME | quote }}
  NEXT_PUBLIC_API_BASE_URL: {{ printf "http://%s-backend:%v" (include "grafana-ai-assistant.fullname" .) .Values.service.backend.port | quote }}
