apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-ai-assistant.fullname" . }}-secret
type: Opaque
stringData:
  PROMETHEUS_TOKEN: {{ .Values.secret.PROMETHEUS_TOKEN | quote }}
  AI_API_KEY: {{ .Values.secret.AI_API_KEY | quote }}
