apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocp-openstack-diagnostic-mcp.fullname" . }}-config
  labels:
    {{- include "ocp-openstack-diagnostic-mcp.labels" . | nindent 4 }}
data:
  clouds.yaml: |
{{ .Values.config.cloudsYaml | indent 4 }}
  policies.yaml: |
{{ .Values.config.policiesYaml | indent 4 }}
  component_k8s_mapping.yaml: |
{{ .Values.config.componentK8sMappingYaml | indent 4 }}
  cli_allowlist.yaml: |
{{ .Values.config.cliAllowlistYaml | indent 4 }}

