apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vm-ip-guide-web.fullname" . }}
  labels:
    {{- include "vm-ip-guide-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vm-ip-guide-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vm-ip-guide-web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: CLOUD_PORTAL_URL
              value: {{ .Values.cloudPortalUrl | quote }}
            - name: CLOUD_PORTAL_URL_DEV
              value: {{ .Values.cloudPortalUrlDev | quote }}
            - name: CLOUD_PORTAL_URL_PROD
              value: {{ .Values.cloudPortalUrlProd | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
